from __future__ import annotations

MODULE_CATALOG = {
    "hab_core": {
        "module_name": "Yaşam Çekirdeği",
        "category": "Habitat",
        "phase_fit": "Faz I",
        "capacity_note": "24 kişi çekirdek kapasite",
        "energy_load": "Orta",
        "reason": "Basınç, medikal ve temel yaşam desteği omurgasını sağlar.",
    },
    "life_support_redundancy": {
        "module_name": "Yaşam Desteği Yedeği",
        "category": "Habitat",
        "phase_fit": "Faz I",
        "capacity_note": "Yedek oksijen ve çevrim hatları",
        "energy_load": "Orta",
        "reason": "Uzun görev ve risk kontrollü operasyon için hayati yedeklilik getirir.",
    },
    "hab_core_2": {
        "module_name": "Yaşam Çekirdeği 2",
        "category": "Habitat",
        "phase_fit": "Faz II",
        "capacity_note": "Ek 24 kişi kapasite",
        "energy_load": "Orta",
        "reason": "Artan ekip boyutu için yerleşim kapasitesini dengeler.",
    },
    "isru_water": {
        "module_name": "ISRU Su Tesisi",
        "category": "Kaynak",
        "phase_fit": "Faz II",
        "capacity_note": "Günlük 14 ton işleme",
        "energy_load": "Yüksek",
        "reason": "Uzun görev süresi için su bağımsızlığını güçlendirir.",
    },
    "power_hub": {
        "module_name": "Enerji Omurgası",
        "category": "Enerji",
        "phase_fit": "Faz I",
        "capacity_note": "Ana dağıtım ve yedek ring",
        "energy_load": "Orta",
        "reason": "Kurulumun ilk fazında enerji dağıtımını stabilize eder.",
    },
    "battery_bank": {
        "module_name": "Yedek Batarya Bankası",
        "category": "Enerji",
        "phase_fit": "Faz II",
        "capacity_note": "Toz haftası tamponu",
        "energy_load": "Düşük",
        "reason": "Toz riskinin enerji akışı üzerindeki etkisini tamponlar.",
    },
    "regolith_shield": {
        "module_name": "Regolit Kalkan Hattı",
        "category": "Güvenlik",
        "phase_fit": "Faz I",
        "capacity_note": "Çekirdek çevresi koruma",
        "energy_load": "Düşük",
        "reason": "Radyasyon ve mikrometeorit maruziyetini azaltır.",
    },
    "maintenance_hangar": {
        "module_name": "Mobil Bakım Hangarı",
        "category": "Operasyon",
        "phase_fit": "Faz II",
        "capacity_note": "12 robot servis hattı",
        "energy_load": "Orta",
        "reason": "Bakım robotlarının sürekliliğini ve toz sonrası toparlanmayı destekler.",
    },
    "manufacturing_pod": {
        "module_name": "Üretim Podu",
        "category": "Sanayi",
        "phase_fit": "Faz III",
        "capacity_note": "Yedek parça ve kabuk üretimi",
        "energy_load": "Yüksek",
        "reason": "Yüksek otonomi hedefi için yerel üretim omurgası kurar.",
    },
    "agri_ring": {
        "module_name": "Tarım Halkası",
        "category": "Gıda",
        "phase_fit": "Faz III",
        "capacity_note": "Toplam ihtiyacın %35-%45'i",
        "energy_load": "Orta",
        "reason": "Uzun süreli yaşam ve gıda kapanışını destekler.",
    },
}
